# Generated by Django 2.0.7 on 2018-12-06 23:06

import apps.accounts.managers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=64, verbose_name='primeiro nome')),
                ('last_name', models.CharField(max_length=64, verbose_name='último nome')),
                ('full_name', models.CharField(blank=True, max_length=128, verbose_name='nome completo')),
                ('email', models.EmailField(max_length=96, unique=True, verbose_name='email')),
                ('email_confirmed', models.DateTimeField(blank=True, null=True, verbose_name='email confirmado')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_volunteer', models.BooleanField(default=False, verbose_name='voluntario')),
                ('profile_image', models.SmallIntegerField(default=1, verbose_name='imagem do perfil')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='accounts/img', verbose_name='image')),
                ('institution', models.CharField(blank=True, max_length=128, verbose_name='nome instituicao')),
                ('is_principal', models.BooleanField(default=False, verbose_name='diretor da escola')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'usuários',
                'verbose_name': 'usuário',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'configurações das contas',
                'verbose_name': 'configurações das contas',
            },
        ),
    ]
