# Generated by Django 2.0.7 on 2018-12-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181207_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('OT', 'Outros')], default='OT', max_length=20, null=True, verbose_name='gênero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduation',
            field=models.CharField(blank=True, choices=[('FD', 'Ensino Fundamental'), ('MD', 'Ensino Médio'), ('SP', 'Ensino Superior'), ('OT', 'Outros')], default='OT', max_length=10, null=True, verbose_name='escolaridade'),
        ),
    ]
