# Generated by Django 2.1.2 on 2018-10-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181020_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['from_date'], 'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
        migrations.AlterField(
            model_name='course',
            name='classmate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='aluno'),
        ),
        migrations.AlterField(
            model_name='course',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='frequencia'),
        ),
        migrations.AlterField(
            model_name='course',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='instituicao de ensino'),
        ),
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='programa'),
        ),
    ]
