# Generated by Django 2.0.7 on 2018-12-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181207_2128'),
        ('courses', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/img', verbose_name='imagem')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('from_date', models.DateTimeField(blank=True, null=True, verbose_name='data de início')),
                ('to_date', models.DateTimeField(blank=True, null=True, verbose_name='data final')),
                ('frequency', models.CharField(blank=True, max_length=100, null=True, verbose_name='frequencia')),
                ('active', models.BooleanField(default=False, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('institution', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Institution', verbose_name='instituicao')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['from_date'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'aula',
                'verbose_name_plural': 'aulas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/img', verbose_name='imagem')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('active', models.BooleanField(default=False, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'programa',
                'verbose_name_plural': 'programas',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/img', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Institution', verbose_name='instituicao'),
        ),
    ]
