# Generated by Django 2.0.7 on 2018-12-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20181210_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classmate',
        ),
    ]
