# Generated by Django 2.0.7 on 2018-12-10 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_classmate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Program', verbose_name='programa'),
        ),
        migrations.AddField(
            model_name='event',
            name='program',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Program', verbose_name='programa'),
        ),
        migrations.AddField(
            model_name='module',
            name='program',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Program', verbose_name='programa'),
        ),
    ]
