# Generated by Django 2.0.7 on 2018-12-11 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_auto_20181210_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_emmit_certification', models.BooleanField(default=False, verbose_name='pode emitir certificado')),
                ('was_achiever', models.BooleanField(default=False, verbose_name='aluno')),
                ('was_adviser', models.BooleanField(default=False, verbose_name='voluntário')),
                ('course', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='curso')),
                ('user', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'participação',
                'verbose_name_plural': 'participações',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_emmit_certification', models.BooleanField(default=False, verbose_name='pode emitir certificado')),
                ('was_achiever', models.BooleanField(default=False, verbose_name='aluno')),
                ('was_adviser', models.BooleanField(default=False, verbose_name='voluntário')),
                ('event', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Event', verbose_name='evento')),
                ('user', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'participação',
                'verbose_name_plural': 'participações',
                'ordering': ['user'],
            },
        ),
    ]
